### ISSUE TITLE
visor shorts: IndexError

### ISSUE THREAD

**Issue by ptrebert** [davidebolo1993/VISOR#1]
Hi Davide,
I am running VISOR version `yesterday's master`. I use the data provided in the `example` folder, `HACk` finished successfully. For `SHORtS --type single-strand`, the following error occurs:

```bash
Traceback (most recent call last):
  File "/TL/epigenetics2/work/pebert/conda/envs/strandsim/bin/VISOR", line 10, in <module>
    sys.exit(main())
  File "/TL/epigenetics2/work/pebert/conda/envs/strandsim/lib/python3.6/site-packages/VISOR/VISOR.py", line 100, in main
    args.func(parser, args)
  File "/TL/epigenetics2/work/pebert/conda/envs/strandsim/lib/python3.6/site-packages/VISOR/VISOR.py", line 160, in run_subtool
    submodule.run(parser,args)
  File "/TL/epigenetics2/work/pebert/conda/envs/strandsim/lib/python3.6/site-packages/VISOR/SHORtS/SHORtS.py", line 238, in run
    if str(entries[3]) not in labels_seen_h1:
  File "pybedtools/cbedtools.pyx", line 523, in pybedtools.cbedtools.Interval.__getitem__
IndexError: field index out of range
```
Best,
Peter

**Comment by ptrebert** [comment]
Yes, so I duplicated the chromosome name for the `LABEL` column - seems to work now, thanks.

+Peter
