### ISSUE TITLE
LASeR issue

### ISSUE THREAD

**Issue by asylvz** [davidebolo1993/VISOR#35]
Hello, I followed the step that you suggested but when generating reads from the fasta files, I get an error after the following command:

`VISOR LASeR -g chr1_t2t.fa -s sims_small/ -b shorts.laser.simple.bed -o laser.2.out --coverage 5
`

But I don't have any issue with SHORtS (same input data)
`VISOR SHORtS -g chr1_t2t.fa -s sims_small/ -b shorts.laser.simple.bed -o laser.1.out --coverage 5
`

Any idea?

```
[09/11/2023 09:45:07][Message] VISOR LASeR v1.1.2
[09/11/2023 09:45:07][Message] Preparing for bulk simulations with a single clone
[09/11/2023 09:45:07][Message] Processing clone 1
[09/11/2023 09:45:07][Message] Processing haplotype 1
[09/11/2023 09:45:07][Message] Simulating from region chr1:1-249430909
[09/11/2023 09:45:07][Message] Preparing simulation from /Users/asoylev/under_development/visor/sims_small/h1.fa. Clone 1. Haplotype 1
[09/11/2023 09:45:09][Message] Simulated coverage for this region will be 2.5
[09/11/2023 09:45:09][Message] Simulating
Process Process-1:
Traceback (most recent call last):
  File "/Users/asoylev/miniconda3/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/asoylev/miniconda3/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/asoylev/miniconda3/lib/python3.9/site-packages/VISOR-1.1-py3.9.egg/VISOR/LASeR/LASeR.py", line 152, in MultiBadRead
    badread_hap_cmd=['badread', 'simulate', '--reference', tmpfa, '--quantity', str(hapcov/c.threads)+'X', '--length', ','.join(str(x) for x in c.length), '--identity', ','.join(str(x) for x in c.identity), '--start_adapter_seq', '', '--end_adapter_seq', '', '--error_model', c.error, '--qscore_model', c.quality, '--junk_reads', str(c.junk), '--random_reads', str(c.random), '--chimeras', str(c.chimeras), '--glitches', ','.join(str(x) for x in c.glitch)]
ZeroDivisionError: float division by zero
[09/11/2023 09:45:09][Message] Mapping simulated reads to the reference genome
[09/11/2023 09:45:18][Message] Processing haplotype 2
[09/11/2023 09:45:18][Message] Simulating from region chr1:1-249430909
[09/11/2023 09:45:18][Message] Preparing simulation from /Users/asoylev/under_development/visor/sims_small/h2.fa. Clone 1. Haplotype 2
[09/11/2023 09:45:19][Message] Simulated coverage for this region will be 2.5
[09/11/2023 09:45:19][Message] Simulating
Process Process-2:
Traceback (most recent call last):
  File "/Users/asoylev/miniconda3/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/asoylev/miniconda3/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/asoylev/miniconda3/lib/python3.9/site-packages/VISOR-1.1-py3.9.egg/VISOR/LASeR/LASeR.py", line 152, in MultiBadRead
    badread_hap_cmd=['badread', 'simulate', '--reference', tmpfa, '--quantity', str(hapcov/c.threads)+'X', '--length', ','.join(str(x) for x in c.length), '--identity', ','.join(str(x) for x in c.identity), '--start_adapter_seq', '', '--end_adapter_seq', '', '--error_model', c.error, '--qscore_model', c.quality, '--junk_reads', str(c.junk), '--random_reads', str(c.random), '--chimeras', str(c.chimeras), '--glitches', ','.join(str(x) for x in c.glitch)]
ZeroDivisionError: float division by zero
[09/11/2023 09:45:20][Message] Mapping simulated reads to the reference genome
[09/11/2023 09:45:28][Message] Merging simulated BAM
[09/11/2023 09:45:28][Message] Done
```

**Comment by davidebolo1993** [comment]
H @asylvz, 

thanks for getting in touch. I'm really late at following up on VISOR's issues due to the very small amount of free time I have. I'm trying to fix things left in the past months. In order to have a sense of what is happening here I need more info on the previous HACk step - like reference, .bed, or haplotypes generated to get to understand if this is reproducible. Thanks,

Davide
